---
# Great examples for Ansible+tor at https://github.com/nusenu/ansible-relayor/
- name: Install tor
  package: name=tor state=present
  become: yes

- name: Configure selinux for tor
  seboolean: name=tor_can_network_relay state=yes persistent=yes
  become: yes
  when: ansible_selinux.status != 'disabled'

- name: Configure firewalld for tor
  firewalld: port={{ item }}/tcp permanent=true state=enabled immediate=true
  become: yes
  with_items:
    - "{{ tor_orport }}"
    - "{{ tor_dirport }}"

- name: Configure torrc
  template:
    src=torrc
    dest={{ tor_config }}
    backup=yes
    owner=root
    group=root
    mode=0644
    validate="tor --verify-config -f %s"
  become: yes
  notify:
    - restart tor
  tags: ['torrc']